### ISSUE TITLE
Cannot start due to circular import

### ISSUE THREAD

**Issue by DTekNOdev** [quaat/ai_space_invaders#1]
```
Traceback (most recent call last):
  File "....\ai_space_invaders\invaders.py", line 24, in <module>
    from invaders import Shield
  File "....\ai_space_invaders\invaders.py", line 24, in <module>
    from invaders import Shield
ImportError: cannot import name 'Shield' from partially initialized module 'invaders' (most likely due to a circular import) (...\ai_space_invaders\invaders.py)
```

invaders.py line 24 tries to import from invaders.py

**Comment by quaat** [comment]
I apologize for the oversight. You are correct that there is a circular import. The issue is now resolved.
